### ISSUE TITLE
不支持属性onStateChange

### ISSUE THREAD

**Issue by dingyuanjie** [react-native-oh-library/react-native-date-picker#16]
Android有，ios没有，harmonyOS Next不支持不支持再在“空闲”和“change”状态之间变化时触发onStateChange，arkts侧DatePicker和TimePicker和TimePickerDialog和DatePickerDialog组件没有该属性，OS不支持。

**Comment by xuxiaoqian1** [comment]
Android独有，harmony不支持，关闭。
